### ISSUE TITLE
Support Self Signed Certificates

### ISSUE THREAD

**Issue by bljohnsondev** [yang991178/fluent-reader#409]
**Is your feature request related to a problem? Please describe.**
I'm using a local RSS aggregator on my local network that is behind a reverse proxy that is using a self signed certificate.  When trying to connect to the Fever API service I'm getting the error:

`handshake failed; returned -1, SSL error code 1, net_error -200`

**Describe the solution you'd like**
I'm assuming this is because it doesn't support self signed certificates.  Any way (via command line maybe?) to tell FR to allow self signed certs?

**Comment by yang991178** [comment]
Electron uses Chromium under the hood, which only trusts its own pool of root certificates. There isn't an Electron API to trust custom certificates except on Linux. The only way to support this would be to provide an option to ignore certificate errors and that would be pretty dangerous.

**Comment by ProfessorCode212** [comment]
@yang991178 Joplin (which also uses Electron) implemented a workaround. It loads the custom certificates from a directory. You can [check it here](https://github.com/laurent22/joplin/issues/191#issuecomment-398585356).

**Comment by t3dium** [comment]
Hm, did this issue end up getting fixed in the end?

Asking because I just tried to use self signed ssl in fluent reader, and it actually worked. The api I tried was the greader api, and I imported the certs into my system (fedora silverblue) using `sudo trust anchor <path-to-cert>`. I haven't tested to see if it works without importing the cert, so that might've been what fixed the issue?

But I do recall this not working for me in the past.
